title: KelasPajakWithLess
description: Mudahnya belajar perpajakan Indonesia
permalink: pretty
twitter_username: kelaspajakwith1
instagram: kelaspajakwith

repository: kelaspajak/kelaspajak.github.io
encoding: UTF-8

exclude:
  - Gemfile*
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - node_modules
  - _submodules
  - script
  - vendor
  - .travis.yml
  - ".git*"
  - bin

markdown: kramdown

sass:
  style: :compressed
  sass_dir: _sass
  load_paths:
    - node_modules

collections:
  fitur:
    output: true
    permalink: /:path:output_ext
    screenshots: /assets/screenshot/logos.jpg


include:
  - _pages


defaults:
  - scope:
      path: ""
      type: fitur
    values:
      layout: detail

plugins:
  - jekyll-mentions
  - jekyll-octicons
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
branch: master

# Google Analytics
google_analytics: UA-146778045-2