kelaspajak:
  image: pajakresources/kelaspajak:1.0
  command: bundle exec jekyll s --force_polling -H 0.0.0.0 -P 4000 --livereload
  ports:
    - 4000:4000
    - 35729:35729
  volumes:
    - .:/srv/jekyll