#!/bin/sh

set -e
export CC=gcc

# echo "==> Installing gem dependencies…"
# which bundle || gem install bundle
# bundle check --path vendor/gems 2>&1 > /dev/null || {
#   time bundle install --binstubs bin --path vendor/gems
# }

echo "==> Getting submodule for docs…"

git submodule update --init --recursive

# ini tambahan sendiri
echo "==> tambahan sendiri"
echo "==> update semua submodules"
git submodule foreach --recursive git fetch
git submodule foreach git merge origin master
echo "==>  add file"
git add .
echo "==> commit"
git commit -am "update submodule"
echo "==> push to submodule..........."

git diff --quiet || {
  echo "===> Committing and pushing changes"
  git commit -am "Sync data"

  REPO=`git config remote.origin.url`

  # If GH_TOKEN environment variable is present, use that to push.
  if [[ -n "$GH_TOKEN" ]]; then
    REPO=${REPO/https:\/\//https://${GH_TOKEN}@}
  fi

  git push $REPO HEAD:submodule
}
echo "==> selesai.........."