#!/bin/sh

case "$TRAVIS_EVENT_TYPE" in
  cron ) script/remote-sync; script/site-test;;
  *    ) script/test;;
esac

#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer ./_site