#!/bin/sh
echo "==> Getting submodule for docs…"

git submodule update --init --recursive

# ini tambahan sendiri
echo "==> tambahan sendiri"
echo "==> update semua submodules"
git submodule foreach --recursive git fetch
git submodule foreach git merge origin master

echo "===> ambil file dari google drive"
#!/bin/bash
fileid="1qZ78V-QKtkuJJ2lhUikr7zzleWrDXsPY"
filename="kup.csv"
curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${fileid}" > /Users/akmal/Documents/GitHub/kelaspajak.github.io/_data/${filename}

fileid="1eI-MuK4bkh7ZFvC4w88xLsJ9Wmsf6Upp"
filename="pph.csv"
curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${fileid}" > /Users/akmal/Documents/GitHub/kelaspajak.github.io/_data/${filename}

fileid="1FGhqqXseAV6tKTOIn6mv7PGU4tvYVb9M"
filename="ppn.csv"
curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${fileid}" > /Users/akmal/Documents/GitHub/kelaspajak.github.io/_data/${filename}

echo "==>  add file"
git add .
echo "==> commit"
git commit -am "update submodule"
echo "==> push to submodule..........."

git diff --quiet || {
  echo "===> Committing and pushing changes"
  git commit -am "Sync data"

  REPO=`git config remote.origin.url`

  # If GH_TOKEN environment variable is present, use that to push.
  if [[ -n "$GH_TOKEN" ]]; then
    REPO=${REPO/https:\/\//https://${GH_TOKEN}@}
  fi

  #git push $REPO HEAD:master
}
echo "==> selesai.........."