name: unit-tests
on:
  pull_request:
    branches:
      - dev
      - releases/v3
  push:
    branches:
      - master
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and Test
        run: |
          npm install
          npm run-script test
      - name: Uploade CodeCov Report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.kelaspajakwithless }} #required
      - name: Rubocop checks
        uses: gimenete/rubocop-action@1.0
