name: unit-tests
on:
  pull_request:
    branches:
      - dev
      - releases/v3
  push:
    branches:
      - master
  
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0


